### ISSUE TITLE
CORS - Angular 6 

### ISSUE THREAD

**Issue by CollinViz** [mevdschee/php-crud-api2#4]
Hello,

Fist thanks you very much for making this API. It saved me a lot of time.

When I use Angular6 to make the web call in chrome I get a CORS error. I commented out Lines 3035 to 3044 (Just the setHeader ) and at the beginning of the file add the below code. This code has worked on all my Angular projects in the past. I am very new to Git so I do not know how to send you the code or to make changes that will become part of the project. (**Only if you want to**).

	// Allow from any origin
	if (isset($_SERVER['HTTP_ORIGIN'])) {
		header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
		header('Access-Control-Allow-Credentials: true');
		header('Access-Control-Max-Age: 86400');    // cache for 1 day
	}

	// Access-Control headers are received during OPTIONS requests
	if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {

		if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
			header("Access-Control-Allow-Methods: GET, POST, OPTIONS");         

		if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
			header("Access-Control-Allow-Headers:        {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

		exit(0);
	}

**Comment by mevdschee** [comment]
Hi @CollinViz , Thank you for using v2 of the api. Can you give me a code snippet to help me reproduce the error?

**Comment by CollinViz** [comment]
Not sure if this will help ?

I think it has something to do with this line in the PHP
$origin = $request->getHeader('ORIGIN');

Remember that the HTTP request is coming from http://localhost:4200/ and I am sending the request to http://localhost:81/
This is my hak
![image](https://user-images.githubusercontent.com/30042726/41562277-6b73dc40-734c-11e8-83b8-5b78eeab8c95.png)

From angular 
private _getdistrictmetroLoadLocal(){
    //province
    this.http.get<any>(this.baseURL + "districtmetro?order=Province_ID",httpOptions).subscribe((customers:any)=>{
      console.log(customers.records);
      this.Districtmetro = [...customers.records]; 
    });
   }

**Comment by mevdschee** [comment]
Ah.. I see it.. thank you very much for this bug report and your help so far.. I have all I need to fix this!

**Comment by mevdschee** [comment]
Please reopen this issue if the problem is not fixed for you in the latest version.
